### ISSUE TITLE
TryMyUI: Start Trial (Business Formation Prototype)

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#1108]
## Tasks

- [x] Finalize interactions in prototype
- [x] Create unmoderated research protocol (google doc)
- [x] Set up TryMyUI Trial & create protocol in TryMyUI
- [x] Publish
- [x] Analyze results

Prototype:
https://www.figma.com/proto/408Krq8roicOzFVYrjwIdE/Navigator-Designs?page-id=6474%3A158222&node-id=6474%3A160334&viewport=264%2C48%2C0.29&scaling=scale-down-width&starting-point-node-id=6474%3A160334&hide-ui=1

**Comment by fiorella-io** [comment]
@aaronvux I've added the prototype link.

**Comment by fiorella-io** [comment]
@aaronvux helped with finalizing the prototype, had it set up on TryMyUI and ran the tests. I'm closing this issue.
