### ISSUE TITLE
Research & Design: Oscar Experience Pt.3

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#1110]
Story: Oscar needs an onboarding flow tailored to their unique circumstances.

## Open Questions

- [ ] Sole proprietorships don't have Entity ID's. What shows in operate for them?

**Part 1**
- [x] Desk Research
- [x] Research Planning

**Part 2**
- [x] User Research: Card Sorts
- [x] Synthesis

**Part 3**
- [x] Design low fi
- [x] Story Mapping
- [ ] Design MVP & gather team feedback
- [ ] [Research planning](https://docs.google.com/document/d/1zijeFu2kGZJivjkPAhYdfZEKQ3jTScKZMNmR_ALapDs/edit#)
- [ ] Testing MVP (Desktop)
  - [ ] Side nav, top nav
  - [ ] Task Screen w calendar
  - [ ] Task screen -- list view
  - [ ] Opportunities screen
  - [ ] Dashboard view
  - [ ] My Business -- Journey Map / card sort, and notification questions. What other information do we need (revenue, demographics)? Do some digging into tools they already?

**Part 4**
- [ ] Testing MVP (Mobile)
- [ ] User flow mapping
- [ ] Story writing

**Misc**
- [ ] What changes for Poppy etc once we roll out these changes?

Oscar needs an onboarding flow tailored to their unique circumstances

Oscar needs a dashboard of managing their business with filings, etc.

Oscar has functions and changes they can address as an operating business:

1. Register your business for tax and employer purposes
2. Change your registered agent/office
3. Amend your certificate of formation, incorporation or authorization
4. Request a Business Registration Certificate
5. Register for PBS (not sure if that is the same as item 1 on this list)
6. Change your tax registration account information online – for example, add or cancel a tax filing obligation (also available via PBS)
