### ISSUE TITLE
Navigator Access - ByPass MyNJ

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1175]
We will track the research and design of bypassing MyNJ account creation to access the Navigator here.

## Action Items
- [ ] Design Review Feedback
- [ ] Finalize:
  - [ ] Floating modal
  - [ ] Popup modal (upon action, after time, etc)
  - [ ] Content restrictions
- [ ] Finalize research plan
- [ ] Conduct moderated tests
- [ ] Conduct umoderated (TMU) tests

**Comment by aaronvux** [comment]
@skeeJay created this ticket to address MyNJ account creation.

**Comment by Jesslax** [comment]
@aaronvux seems like a duplicate of #999. Consider deleting.

**Comment by carye3** [comment]
Issue if user tries to create a new Navigator login, but has an existing MyNJ and can't login: 
![image](https://user-images.githubusercontent.com/62653834/151811638-25c2a178-e21a-4a7d-b626-ed4f3d2e928d.png)
@fiorella-io @aaronvux
