### ISSUE TITLE
Design: Update Poppy task screens 

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#1216]
Could we explore a design for the task screen that makes it feel like there is less copy, or create some kind of hierarchy around the copy. 

## Tasks
- [x] Review w Jess & Ce
- [x] Ce to send list of sample tasks to Design
- [x] Design
- [x] Design Review
- [x] Incorporate changes
- [x] Testing (moderated)
- [x] Meet with Ce & Jess about findings
- [x] Incorporate findings
- [x] Present in Design Review

## Notes:
Most Poppy tasks will have some if not all of the following:

1) title
2) description
3) to complete this application you need
4) after you complete this task you will have
5) name of agency who distributes the form
6) name/# of form
7) CTA (link)

## Designs
[Desktop](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=8711%3A200323)
[Mobile](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=8711%3A200629)

**Comment by carye3** [comment]
Would like to include the structure we heard from users: 

1. What's mandatory (and what's the penalty)
2. What's recommended

**Comment by carye3** [comment]
@CeciliaRam friendly reminder to send the list of sample tasks that we can experiment with

**Comment by CeciliaRam** [comment]
@carye3 here you go: https://docs.google.com/document/d/1CByoEcxZhFcOgG9HLSwHoG4NjLg7OH3XUgPoLDsqVUE/edit#

**Comment by carye3** [comment]
@aaronvux this is ready for development
