### ISSUE TITLE
Design: Updated Profile Page with Documents

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#1277]
As a user, i need to be able to easily access any documents created in the Navigator (eg business formation) in order to use them in the future.

## Potential Features:
- [ ] Business Info Page: S-Corp, Business Formation
- [ ] Personal Info (account info if necessary)
- [ ] Important Info page: documents (business formation docs, welcome letter), important numbers incl. tax Pin (from welcome letter)
- [ ] Oscar version: Remember to include adding business formation date, Number of Employees and Certifications

## Notes

- [ ] User testing
- [ ] UX Review
- [ ] Content approval

**Comment by carye3** [comment]
@fiorella-io @aaronvux need this in tandem with #1205
