### ISSUE TITLE
Google Analytics Additions

### ISSUE THREAD

**Issue by skeeJay** [newjersey/navigator.business.nj.gov#1328]
### Events

- [x] onboarding_first_step/arrive/arrive_from_myNJ_registration
-- Note: non-interactive event
- [x] onboarding_last_step/submit/finish_onboarding
-- Note: Anne has already implemented an internal count for people who “finish” onboarding and this can be tied to the same event handler, so we get the same count
- [x] account_name/click/expand_account_menu
- [x] account_menu_myNJ_account/click/go_to_myNJ_home
- [x] account_menu_my_profile/click/go_to_profile_screen
- [x] task_business_name_check_availability/submit/view_business_name_availability

## Notes

- [x] See https://docs.google.com/document/d/1SbuKxnvqEXZXP4-eGG7_-Mb-SlhDtmawEHXV8cn5Er4/edit?usp=sharing for full specification

**Comment by aaronvux** [comment]
moving to staging.
