### ISSUE TITLE
Two Column Design in Business Formation

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1331]
As Poppy, I need a more streamlined experience when forming my business so I don't have to scroll an inordinately long page.

## Acceptance criteria
- Implement 2 column design.

## Design

Desktop:
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6601%3A147611

Mobile:
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=7116%3A168284

## Additional Acceptance Criteria:
- Follows Design
- Works in Mobile
- 508 Compliant

## Notes
- [x] UX Review
- [x] PO Approval

**Comment by aaronvux** [comment]
@fiorella-io please add Business Name validation design to this story.

**Comment by namanaman** [comment]
@carye3 @fiorella-io Specifically for the desktop version of the "Add Members" modal where the state is not disabled and set to NJ, I made the State dropdown take up more space and the ZIP code take less space than the design had. I've also updated it to only show state abbreviations. This avoids issues where the state input and dropdown get super crowded. Is this okay?

Updated Width:
<img width="648" alt="Fixed State Dropdown" src="https://user-images.githubusercontent.com/9057802/153446811-e262187a-cc3d-4ea1-9d22-a007b903d034.png">

Design Width:
<img width="960" alt="Gross State Dropdown" src="https://user-images.githubusercontent.com/9057802/153446814-3ec2b44f-a7c5-4c36-b1de-8f2cc9618c4a.png">

**Comment by aaronvux** [comment]
@fiorella-io please review.  I'm seeing the Location City not matching the design.  Do we need to talk about this one?

**Comment by fiorella-io** [comment]
@namanaman Can you adjust the following:

- [ ] Add (Optional) for Address Line 2
- [ ] Registered Agent Mobile: For the radio buttons, there seems to be some padding-right that is making the radio options wrap to too many lines
![image](https://user-images.githubusercontent.com/91498500/153667596-3d2ab6cc-b951-42b4-b123-7e651a14ceb2.png)

- [ ]  Mobile: Increase the height of the "Start Forming My Business" button
![image](https://user-images.githubusercontent.com/91498500/153667723-32a3590b-39e1-410d-9571-508aafb2df94.png)

- [ ] For the Payment page, we are missing a divider line below Phone, as well as the "Services" heading and description. I'm not sure if the content needs to add the copy but we do need the divider line. @CeciliaRam @Jesslax 
<img width="758" alt="image" src="https://user-images.githubusercontent.com/91498500/153668390-6b86b721-67fc-417b-9019-42e8275374a5.png">

**Comment by namanaman** [comment]
@fiorella-io Changes can be reviewed

**Comment by fiorella-io** [comment]
@namanaman Looks good! Thank you, Naman!
