### ISSUE TITLE
Update Business Formation Payment Type Design

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1333]
As Poppy, I need the ability to easily comprehend and select the payment type in the Business Formation Form so that I can obtain my Entity ID easily.

## Acceptance criteria
- Update payment table with radio buttons for Payment Type
- Correctly show the Total of all selected billable items.
- Selected State is green and bold.
- Validate the Payment Type field.
-- Refer to design for field validation, continue current page validation.
- Follow Design for Page Layout

## Design
Desktop:
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6474%3A159297

Mobile:
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=7383%3A170252

## Additional Acceptance Criteria:
- Follows Design
- Works in Mobile
- 508 Compliant

## Notes
- [ ] UX Review
- [ ] Content Review
- [ ] PO Approval

**Comment by aaronvux** [comment]
Waiting on pointing for 508 feedback on the table element.

**Comment by aaronvux** [comment]
@FarazA22 can you pick this one up as your next story?

**Comment by aaronvux** [comment]
@mikewolfd I thought we said we weren't defaulting the payment type which is why there is a validation.

**Comment by mikewolfd** [comment]
There's no default, but if you already had gone through the process it saved your choice

**Comment by aaronvux** [comment]
@fiorella-io please review

**Comment by aaronvux** [comment]
@mikewolfd 

- [ ] update price of Certified Copy of Formation doc to $25.00

**Pay with Credit Card**
- [ ] Add additional $2.00 to Pay with Credit Card Total if Certificate of Standing is selected
- [ ] Add additional $2.00 to Pay with Credit Card Total if Certified Copy of Formation is selected.

**Pay with E-Check**
- [ ] Add additional $1.00 to Pay with Credit Card Total if Certificate of Standing is selected
- [ ] Add additional $1.00 to Pay with Credit Card Total if Certified Copy of Formation is selected.

**Comment by mikewolfd** [comment]
@fiorella-io the line/header/description is already there exactly as it is in the Figma design?

That wasn't part of the acceptance criteria, but I can update the other table.

**Comment by fiorella-io** [comment]
@mikewolfd  Yes, Naman just added it, thanks

**Comment by mikewolfd** [comment]
@aaronvux @fiorella-io it should all be up

**Comment by aaronvux** [comment]
@mikewolfd should be 

$3.50 for Official Formation Documentation
$2.00 for Certificate of Standing
$2.00 for Certified Copy.

Currently all three are adding $3.50

**Comment by fiorella-io** [comment]
@Jesslax @CeciliaRam I don't see the contextual information when I click on any of the documents listed.

**Comment by CeciliaRam** [comment]
@fiorella-io @Jesslax, looking into it

**Comment by fiorella-io** [comment]
Thank you @mikewolfd and @CeciliaRam! Everything looks good!

**Comment by aaronvux** [comment]
This is good!
