### ISSUE TITLE
Add Ability to See Massage License Status

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1393]
As Poppy,  I need access to a Massage specific Permitting Page in the Navigator so I can easily ensure I have all the necessary items completed in order to submit my application.

## Acceptance criteria

- Create Checklist of items necessary to submit Massage license application for the new tasks below
- Replicate design & functionality of Cosmetology license
- Follow Google Doc for Content
https://docs.google.com/document/d/1Jg0y19_AeiJaeHqSi9PTTxUhyhK0cyBBXPp5sRJMf_M/edit

## Standard Acceptance Criteria

- Works in Mobile
- Follows Design
- 508 Compliant

## Standard Acceptance Criteria
- Works in Mobile
- Follows Design
- 508 Compliant

## Design
TBD

## Notes
- [ ] UX Review
- [ ] Content Approval
- [ ] PO Approval

**Comment by FarazA22** [comment]
@CeciliaRam @Jesslax FYI - The dependency array contains a list of markdown files by filename. If the task is not completed, it will be included in the "we recommend you look at" alert. I've added the form-business-entity-llc markdown file to the array in the doc since this is a separate markdown document.

**Comment by FarazA22** [comment]
@aaronvux Ready for review. Sending you the test data file via slack.

**Comment by aaronvux** [comment]
License status check for pending and approved is working.  @Jesslax @CeciliaRam please check for content.  @fiorella-io @carye3 please review the design.

**Comment by carye3** [comment]
Looks good @aaronvux @dsueltenfuss!

I have some cosmetic changes, but don't want to hold up delivery so the following can wait to a dev:design pairing @FarazA22 

- [ ] Please add padding of 26px to the right of the tooltip icon <img width="331" alt="image" src="https://user-images.githubusercontent.com/62653834/158408646-4f89f856-8359-4aef-aec8-77e8c288a0cc.png">
- [ ] We've noted this before, but this contextual info-linked text should wrap properly <img width="648" alt="image" src="https://user-images.githubusercontent.com/62653834/158409801-f974d90b-2b71-4464-a33a-096df78007fc.png">
- [ ] Loading animation is not centered in the button <img width="143" alt="image" src="https://user-images.githubusercontent.com/62653834/158409639-7a2b17e8-f81f-4d25-8f78-19f75cb2562a.png">
