### ISSUE TITLE
Design & Content: Onboarding Industry List (for dynamic funding list)

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#1398]
## Tasks 
- [x] Meeting: fiorella, jess, cary, ce
- [ ] Jess to send industry categories and sub-categories lists to Design
- [ ] Design:
  - [ ] Industry list in Onboarding
  - [ ] Opportunities list: opps with industry-specific headers
- [ ] Send to Content for feedback
- [ ] Testing

**Comment by carye3** [comment]
@Jesslax a reminder to send Fiorella and I (here preferably) the list of industry categories and sub-categories

**Comment by carye3** [comment]
Final list:

Accommodation and Food Services
-restaurant
-food truck
Administrative and Employment Services
-cleaning aid
-employment agency
-janitorial services
Agriculture, Forestry, and Fishing and Hunting
Arts, Entertainment, and Recreation
Clean Energy
Construction
-home improvement contractor
Digital and Print Media
Educational Services
Finance, Insurance and Professional Services
Health Care and Social Assistance
-home-health aide
Industries not classified
Life Sciences
Manufacturing
Mining, Quarrying, and Oil and Gas Extraction
Offshore Wind
Organizational or Financial Management Companies
Other Services (except Public Administration)
-cosmetology
Professional, Scientific and Technical Services
Real Estate and Rental and Leasing
Retail Trade
-retail
-pharmacy
Technology
Transportation and Warehousing
-auto body repair
- non-medical transport
Utilities
Waste Management
Wholesale Trade

e-commerce can be any of these!
