### ISSUE TITLE
Design a Way to Handle Industries That Are Missing Step 2 in their Roadmap

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1399]
## Tasks
- [x] 30 min discussion with Content & Design
- [ ] Design:
  - [ ] V1: remove step 2 from all roadmaps & renumber
  - [ ] V2: remove step 2 conditionally (per industry)
  - [ ] V3: Step 2 remains, says "you don't have any tasks"
  - [ ] Compile pros & cons list for each
- [ ] Design Review
- [ ] Test?

**Comment by aaronvux** [comment]
This work will encompass the Consulting Industry needs.
