### ISSUE TITLE
Google Analytics - Business Formation Round 2

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#1444]
## Acceptance criteria
Add:
- [x] - business_formation_business_name_edit/click/go_to_name_search_step 
- [x] - business_formation_legal_structure_edit/click/show_legal_structure_modal 
- [x] - business_formation_legal_structure_modal/submit/go_to_profile_screen 
- [x] - business_formation_success_screen/arrive/arrive_from_NIC_formation_processing [non-interactive-type event]

Validate this event is not firing and no longer applicable:
- [x] business_formation_name_step_update_name_on_roadmap/click/update_name_on_roadmap 

Validate this event is firing:
- [x] business_formation_billing_step_continue_button/click/go_to_next_formation_step

## Notes
- [ ] PO Approval
- [ ] Full spec: https://docs.google.com/document/d/1SbuKxnvqEXZXP4-eGG7_-Mb-SlhDtmawEHXV8cn5Er4/edit?usp=sharing

**Comment by aloverso** [comment]
@aaronvux @skeeJay ready for review

**Comment by kmelefsky** [comment]
test in production
