### ISSUE TITLE
Design: Graduation / Toggle between Poppy and Oscar

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#1528]
## Tasks

- [x] Discuss design options with EJ, Jess, Aaron
- [x] Design 2 Versions
  - [x] MVP
  - [x] Longer term version
  - [x] In both, address consolidated Industries / Sectors list in https://github.com/newjersey/navigator.business.nj.gov/projects/2#card-76359078
- [ ] @Jesslax for users who selected "all other" in Sector dropdown in onboarding, we need to include that question in onboarding modal 2.14.22

## Acceptance Criteria
- [ ] If you have complete Business Formation, you do not see the business formation question in graduation modal

**Comment by FarazA22** [comment]
MUI will make the dialog component scrollable. Sharing a link to the [MUI - Dialog](https://mui.com/components/dialogs)

<img width="472" alt="Screen Shot 2022-02-15 at 1 20 54 PM" src="https://user-images.githubusercontent.com/72581979/154124546-06f2a9b3-9f3e-429d-bb36-728d6c7d30d5.png">
