### ISSUE TITLE
Design System: Add Input Field & Dropdown Assets

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#1550]
As a design team, we need consistent input fields and dropdown menus in order to avoid inefficient work.

## Tasks
- [ ] Take screenshots of inconsistent input field spacing etc
- [ ] Bring to dev:design sync
- [ ] Create components in design system
- [ ] Update all previous designs to include new components

**Comment by carye3** [comment]
@kmelefsky @aaronvux we'd like to add this to Sprint 29
