### ISSUE TITLE
Design System: Inconsistencies Audit

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#1551]
## Tasks
- [ ] Take screenshots of inconsistencies
- [ ] Do a few hour long audit sessions per sprint in Storybook
- [ ] Update components / create tickets for new components afterward

**For when new designer is onboarded**
