### ISSUE TITLE
Design: Cannabis

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#1696]
## Tasks
- [ ] Design:
  - [x] Microbusiness: Question (Y/N) vs Dropdown vs Radio button
  - [x] #2041

## Old Tasks
- [x] Design
  - [x] Task: Apply for Your Cannabis Permit Task
  - [ ] Task: Priority Status
  - [x] Pattern: Dynamic Task Format
  - [x] Pattern: Long requirements list in task format
- [x] Design Review / Jess & Ce Feedback
- [x] Prepare prototype:
  - [x]  with entire(?) flow for Cannabis (see google doc)
  - [x] A/B Tests for dynamic task formatting, long requirements lists
- [x] Test
- [ ] Incorporate feedback

## Design Considerations
- [ ] Simplifying very long lists of requirements
- [ ] Dynamically changing task lists based on preliminary questions

## Design:
[Priority Status Eligibility Task](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=11438%3A174751)
[Cannabis License Task](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=11438%3A176801)

## Notes
- [Cannabis Roadmap Google Doc](https://docs.google.com/document/d/14qDBJRcttoM-4hVzgX9EZgm8wUiU6o8eyMF3bo0yzoQ/edit#)

**Comment by carye3** [comment]
Note for content: replace "business size" quesiton with "Are you a microbusiness? y or no"
