### ISSUE TITLE
Design: Pick 508 Compliance & Design System Mgmt Training Opps

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#1757]
As design team, we need to understand 508 & design system best practices in order to design accessible and consistent products

## Tasks
- [x] Fiorella to attend conference https://www.deque.com/axe-con/schedule/
- [ ] Cary to watch 1 youtube video from axe con conference
- [ ] Cary to chat with Rachel
