### ISSUE TITLE
Design: Make Navigator More Prominent on Biz.NJ

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#1838]
make Navigator more prominent, elevate Navigator to nav, hero, etc

## Tasks
- [ ] Design 2 versions
- [ ] DR and incorporate feedback
- [ ] Content review
- [ ] Test
- [ ] DR & incorp feedback

## Considerations
- [ ] Hero banner on homepage. / carousel
- [ ] Tiles (deprioritize funding tiles)
- [ ] Sidebar callout
- [ ] Intercom?
  - [ ] Are reps able to tell where user is originating?

**Comment by fiorella-io** [comment]
make Navigator more prominent, elevate Navigator to nav, hero, etc
