### ISSUE TITLE
Design: Update landing page for Oscar

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#1840]
## Tasks
- [ ] Discovery
  - [x] Gather inspiration
  - [x] Review [initial content](https://docs.google.com/document/d/1X0im0Tn8N5Gxt4BkLAtkwx3OqwHfD_mOfqW2JOLnIaE/edit#heading=h.qmxl28gyoeqi) by Jess
- [ ] Design 2-3 versions:
  - [x] 3 Wireframe options
    - [x] Value-forward
    - [x] Feature-forward
    - [x] Hybrid
- [ ] DR and incorporate feedback
- [ ] Content review
- [ ] Test
- [ ] DR & incorp feedback
