### ISSUE TITLE
Design: Improve How Users Give Feedback

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#1841]
Current banner bar has low survey turnout, we'd like to increase survey turnout
Survey is being used as a way for users to tell us when there is a bug, this is diluting the survey data, we should consider exploring a way to separate survey feedback verse access issues
Survey is currently only for Poppy experience but we need a different survey for Oscar

## Tasks
- [x] Initial discussion with team
- [ ] Follow-up exploration
  - [ ] Research: bug reporting, feature requests, survey responses best practices. Examples: XD, Miro...
  - [x] Compare response rate via pop-up vs beta bar vs intercom (ask Joe)
- [ ] Design
  - [ ] Create 1-2 user flows showing how to route data to which internal actors (dev, BAC, etc)
- [ ] Present options 
  - [ ] (flows, current data, and research) to team (DR)
  - [ ] Technical constraints (what applications should / can we use?)
- [ ] Design
  - [ ] Compile team needs for feedback (bugs, features, & general survey)
  - [ ] 2-3 versions
- [ ] Design? (Next Sprint?)

## Acceptance Criteria
- Jotform: detect automatically whether its a Poppy or Oscar, direct them to appropriate survey

## Metrics
- Banner bar: 
  - Baseline .1% of users click on it
  - How much is that increasing?
- Bug report / feature request form:
  - Capture screen width and device type automatically

## Considerations
- [ ] Just for Navigator, or for B.NJ as well?
- [ ] Joe: overview of Intercom feedback
- [ ] Internal ideation session: design & strategy
- [ ] Explore how to incorporate existing feedback into UserBit
- [ ] Design: revisit design of current pop-up (Intercom) survey in Navigator
