### ISSUE TITLE
Design/Discovery Exploration: UX Metrics & ROI

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#1904]
As a design team, we need to know the baseline & goal user experience metrics so we can measure our progress toward those goals.

Initial metrics breakdown [here](https://miro.com/app/board/o9J_lzXPVyw=/?moveToWidget=3074457363696435959&cot=14)

## Tasks
- [x] Kickoff Meeting
  - [ ] Gather BFS KPI's
  - [ ] Extract UX-related KPI's
- [ ] Schedule UX metrics meeting for every 4 weeks
- [ ] Hold a 1-hour DT (Design Team) metrics meeting using Miro board and HEART framework
