### ISSUE TITLE
Discovery: Explore ways to get more people to fill surveys, perhaps a separate way to report bugs

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#1906]
## Tasks
- [ ] Initial ideation with EJ
- [ ] Joe: overview of Intercom feedback
- [ ] Internal ideation session: design & strategy
- [ ] Explore how to incorporate existing feedback into UserBit
- [ ] Design: revisit design of current pop-up (Intercom) survey in Navigator

## Considerations
- [ ] Just for Navigator, or for B.NJ as well?
