### ISSUE TITLE
Design/Content: Navigator Style Guide

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#1928]
As a discovery team, we need consistent content and design standards in order to add features and content to the Navigator efficiently and in a way that is consistent and predictable to the user.

## Tasks
- [ ] Figure out a format that works for both content and design
- [ ] 1-hour meeting to produce first draft style guide
- [ ] Regular meetings thereafter to keep style guide up-to-date

## Considerations
- This might make most sense after the product is a bit more mature (after "gradual graduation" has been explored?)
