### ISSUE TITLE
Research business requirements for Pharmacy license applications

### ISSUE THREAD

**Issue by skeeJay** [newjersey/navigator.business.nj.gov#194]
Activities include:

- [x] Agency Research: getting Community Affairs to work on this with us
- [x] developing the roadmap / user research where applicable
- [x] Design: probably not happening for next 1-2 sprints (10.25.21)

**Comment by skeeJay** [comment]
Conversation scheduled with the ED of Pharmacies on 11/3.

**Comment by skeeJay** [comment]
Had a good initial conversation with Anthony. Next steps are probably 1) @Jesslax @CeciliaRam continue research of a Pharmacy Roadmap, with Anthony and other SMEs, and 2) @aloverso @mikewolfd have a conversation with Joe Schweitzer and Cheryl to connect to the right data. cc @kmelefsky

**Comment by Jesslax** [comment]
@skeeJay let's do it, it always takes a little while to get these meetings on the calendar.

**Comment by Jesslax** [comment]
Believe we can start story writing and design @aaronvux @carye3:

Initial sketch:
[](https://docs.google.com/document/d/1ArR16Smhza8Mr0bss4ZRHZMv2Fl8S_qQRDrH-Q-1UYg/edit?usp=sharing)

**Comment by Jesslax** [comment]
@aaronvux as we discussed on tuesday, this is ready for design/stories. I have a few small items I need to finish researching, but they are just copy. Not sure how you want to handle this tkt, if you want to close, or reuse for design.

**Comment by aaronvux** [comment]
Moving this to resolved column.

**Comment by Jesslax** [comment]
@aaronvux research is done, but content dev isn't. Should we keep this open? Or create another tkt?
