### ISSUE TITLE
Design: Navigator Landing Page Style / Branding

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#1962]
## Tasks
- [ ] Discovery
  - [x] Gather inspiration
  - [x] Review [initial content](https://docs.google.com/document/d/1X0im0Tn8N5Gxt4BkLAtkwx3OqwHfD_mOfqW2JOLnIaE/edit#heading=h.qmxl28gyoeqi) by Jess
- [ ] Design 2-3 versions:
  - [ ] Style Options (Mood Board)
    - [ ] Illustration Packs - Figurative
    - [x] Photo Options (1-2 photos) with strong preference against (compare with similar products, differentiate B.NJ and Navigator, ability to project yourself)
    - [ ] Illustration Pack - Abstract
  - [ ] Themes (Mood Board)
    - [ ] Navigation
    - [x] Growth
    - [x] Collaboration
- [ ] DR and incorporate feedback
- [ ] Content review
- [ ] Test
- [ ] DR & incorp feedback
