### ISSUE TITLE
Design: Consistent Error Messages

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#2039]
As a user, I need consistent feedback about system errors so I can respond efficiently while keeping cognitive load low.

Mural [here](https://app.mural.co/t/officeofinnovation7132/m/officeofinnovation7132/1647451998940/aa14bde1dc5c2255a224738a21c0fb6b7df2a669?wid=0-1649961728666)

## Tasks New
- [ ] Identify all alert levels needed (Snack bar, In-Page, In-Section?, and In-line)
  - [ ] What do consolidated alerts look like? IE bulleted list
  - [ ] Do we need section-level alerts?
- [ ] Talk to accessibility experts (Coforma, Fearless)
- [ ] Decide who to handle tabbing logic (Future)

## Accessibility
- [ ] Move the focus to the first form control that has the error or move the focus to the common error message.
   - [ ] If common error, list all the fields that need to be fixed with anchor links to take the user to that specific field
- [ ] In-section alert is not prominent, 
- [ ] Inline errors need another visual treatment other than color alone since some users can have a sensitivity to red or are colorblind. Follow [USWDS](https://designsystem.digital.gov/components/text-input/)
- [ ] Remove placeholder text globally ([Is not accessible](https://www.deque.com/blog/accessible-forms-the-problem-with-placeholders/), [NN/g best practices](https://www.nngroup.com/articles/form-design-placeholders/))
- [ ] Be more explicit with our messaging. for example if the email field is not valid, instead of displaying the error message as “invalid email,” display “invalid email enter **example@yourdomain.com**”.
- [ ] Make sure required fields have [HTML5 and ARIA required attributes](https://www.deque.com/blog/anatomy-of-accessible-forms-required-form-fields/)
- [ ] Possibly add an asterisk to identify anything that is required
- [ ] Anything labeled edit would include the item that needs to be edited. Example Edit Purpose, Edit Provisions. 

## Tasks
- [x] Establish error message pattern (top, slim)
- [ ] Review error messages that are non-compliant (prioritize Formation)
- [ ] Discuss with Faraz during Dev:Design

## Notes
- [ ] Business Formation ([slack thread](https://njcio.slack.com/archives/CQNBLAZ41/p1649941626067609?thread_ts=1649940747.052599&cid=CQNBLAZ41)): the response from the API <img width="1440" alt="Screen Shot 2022-04-14 at 8 51 04 AM" src="https://user-images.githubusercontent.com/62653834/163405323-436062f9-d302-4fd2-adfb-8b09bf8b468d.png">

![Error1](https://user-images.githubusercontent.com/62653834/158656726-36859efe-9186-4fc8-9e0c-12c923241876.png)
![Error2](https://user-images.githubusercontent.com/62653834/158656739-50126d45-b0af-467e-a471-73814b475fe2.png)
- [ ] 3 second snackbar is too short

**Comment by carye3** [comment]
<img width="113" alt="image" src="https://user-images.githubusercontent.com/62653834/159051577-b8e21cb8-9786-4767-bcfe-8adfe8c138f6.png">
