### ISSUE TITLE
Design: Consistent Pattern for Steppers, Tabs, and Button Progression

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#2041]
As a user, i need to clearly identify multi-step detail screens by whether they are informational, integrated, or status-related in order to understand the extent of their functionality.

## Tasks
- [x] Audit of different multi-step detail screens
- [ ] Designing different version for each
  - [ ] Steppers for integrated forms (business formation) (have a beginning and an end)
  - [ ] Buttons for multi-step informational detail screens
  - [ ] Tabs for ??? Recommend new story
- [ ] Design review 
- [ ] Incorporate feedback
- [ ] Testing
