### ISSUE TITLE
Design Research (Preliminary): Formation for other legal structures

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#2044]
## Tasks (Sprint 31)
- [ ] Initial sync with Ce on researching adding other legal structures to formation, incl. C-Corp, LP, LLP

## Tasks (Sprint 32)
- [ ] Pull screenshots / user flows for each treasury business formation form
- [ ] Align form steps as much as possible to the existing business formation task pattern (preferably within "Business" step)
- [ ] Design
- [ ] Design review
- [ ] iterate
- [ ] Test
- [ ] Finalize

## Considerations
- We are building this with the assumption that Navigator will at one point know their legal structure via Treasury API

## Reference
- [Ce's C-Corp research](https://docs.google.com/document/d/1KifIyjLEh-Q_1XFJ-rTI7C5mscWWsnprb0JIWxkC4hU/edit#heading=h.3oj31og58ovt)
