### ISSUE TITLE
Update Determine if You are Eligible for Priority Status Task

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#2081]
As Poppy, I need to have information dynamically displayed for my Cannabis License application so I have the correct information.

Acceptance criteria
Determine if You are Eligible for Priority Status Task

Dependencies: Formed My Business, Registered for Taxes
Copy:
Priority applicants will receive priority review and approval in the application process. Having more than one [priority status](https://www.nj.gov/cannabis/businesses/priority-applications/) does not increase your priority. Learn more about how priority status is reviewed and approved.
Question: Which of the following priorities do you qualify for (listed in order of their priority status):
Check box list (contextual links)
Diversely Owned Businesses
Social Equity Businesses
Impact Zone Businesses
None of the above (logic: unselect any previous items if selected)
Priority Logic

If Impact Zone Business or Social Equity Business is selected, display the following copy:
You do not need to file a separate application to claim Impact Zone Business Priority or Diversely Owned Business Priority, this will be part of your Cannabis application.
If None of the above is selected, display following copy:
No further action is required.
If Diversely Owned Business is selected, display:
Copy: You need to obtain a certificate from the NJ Department of Treasury.
CTA button: [Apply For My Diversely Owned Business Certification](https://www.njportal.com/DOR/SBERegistry/)

**Comment by FarazA22** [comment]
@aaronvux @carye3 @fiorella-io 
## Questions for Priority Types section/ checkbox list
- [ ] The content for the 4th bullet is not consistent with the content noted in the design. Which one are we using?
- [ ] The 6th bullet item is missing from the design. Do we need to update the design or remove it from the AC? Note: the impact zone contextual link includes a criteria section which contains a list, the order of that list is as follows: 1) located in, 2) owned by, and 3) employing residents. If this bullet is included, I suggest we swap the 5th and 6th bullet items in the AC so it’s consistent with the order in the contextual link

**Requesting Design**
- [ ] The 8th items has a contextual link in the AC, but is not included in the design. Should there be one / can we update the design? 

## Questions for Application Needs section
- [ ] AC describes for sections: M/WBE, VOB, IZ, and SEB. Do markdown files exist for each section? I don't think they have been created, but wanted to confirm. If not, the AC should be updated to include the content of each section.

**Requesting Design**
- [ ] AC mentioned multiple options can render on the second 'tab' / Application Needs section. Can you provide a design for a scenario where all options are selected. If content doesn't exist, I'd like to see a design that shows a collapsed section (M/WBE, VOB, or SEB) and expanded (IZ section). The AC mentioned displaying "Your Done" when impact zone is selected, I need more clarity on how this would look. Would the UI be different if IZ was the only section that displayed? If so, I would need a design for that UI as well.
- [ ] I need a design if the "None of the above" is checked by the user.

**Comment by aaronvux** [comment]
@FarazA22 can we stay on after standup tomorrow to go over this together?

**Comment by carye3** [comment]
@Jesslax should we add Disabled Veteran Owned cert to this list?

**Comment by carye3** [comment]
@aaronvux Separate story: once a user has applied for a certification here, then that certification is either (A) removed from the Opportunities list or (B) labeled as "Applied"

**Comment by aaronvux** [comment]
@CeciliaRam will add the dependencies

**Comment by aaronvux** [comment]
@Jesslax it looks like there are two content files for the certifications, one for Oscar and one for Poppy.   Do we want there to be checkboxes for both experiences?  We can discuss at standup.

**Comment by Jesslax** [comment]
If we want to connect the certification experience between Cannabis Poppy and Oscar I think it should be a separate tkt to explore. But it is not worth prioritizing to me.

**Comment by FarazA22** [comment]
@CeciliaRam I've added a "Certification Checklist" collection within the CMS. Can you review the three md files to confirm they are complete. The Social Equity one only has an example checkbox. 

Also, the design below has a `apply for certification here` checkbox and a `apply for my certification` button at the bottom. Is the checkbox required if the button will direct the user to the external site?
<img width="486" alt="Screen Shot 2022-04-18 at 6 11 51 PM" src="https://user-images.githubusercontent.com/72581979/163885703-076958ed-0e36-4724-8c1b-d069ca126d6c.png">

**Comment by CeciliaRam** [comment]
@FarazA22 confirmed with Jess that that "apply here" item can be removed. 
(Already chatted on slack about the collection in Netlify and the checkboxes not showing - just making a note of it here. Can check the collection again when it's ready.)

**Comment by FarazA22** [comment]
@carye3 @fiorella-io Can you please take a look at this design - the layout needs to be fixed
https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs-(Sprint-1-32)?node-id=11495%3A184196

**Comment by aloverso** [comment]
@aaronvux ready for review

**Comment by aaronvux** [comment]
@aloverso @FarazA22 this looks awesome at first pass!  @carye3 @fiorella-io @Jesslax @CeciliaRam please review.

**Comment by CeciliaRam** [comment]
@aaronvux looks great, works great!

**Comment by Jesslax** [comment]
@aaronvux  Looks great, nice work all

**Comment by fiorella-io** [comment]
@FarazA22 for mobile (320px) we need to stack all the CTA buttons.
![image](https://user-images.githubusercontent.com/91498500/164719539-41e09454-ea3c-4c21-8b34-2e6145830d5c.png)

**Comment by aloverso** [comment]
@fiorella-io this is fixed

**Comment by fiorella-io** [comment]
Looks good! Thanks, @aloverso

**Comment by aaronvux** [comment]
I believe this is ready to deploy if there aren't any more content changes necessary.

**Comment by Jesslax** [comment]
@aloverso sorry but I have a few copy corrections, if I am able to change this myself, please let me know

50% or more of your business is owned by a veteran (context link) please change to 50% or more of your business is owned by a disabled veteran (no context link)
AND
The copy on the top of the 2nd page, I'd like to change to:
Below are the priority statuses you are eligible for. Diversely-Owned Businesses will have the highest priority followed by Social Equity Businesses and Impact Zone Businesses. 

Having multiple priorities does not give you an additional advantage.

**Comment by Jesslax** [comment]
Good to go!
