### ISSUE TITLE
Design: Gradual Graduation - Oscar sidebar for Poppy

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#2396]
## Tasks
- [x] Welcome (Closable when opportunities are unlocked)
- [x] Registration Reminder
- [x] Registration Success message
- [ ] Reminder: unlock opps and certs (unclosable?)
- [ ] Graduation toggle? Maybe not

## Notes

- initial merge of Oscar sidebar into Poppy experience; implementation-wise, this would allow dev to refactor the Poppy experience into the same layout as Oscar
