### ISSUE TITLE
Design: Industry Dropdown UX Improvements

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#2400]
As Poppy, i need to easily identify my industry from the options available and be confident that my selection is sufficient in order to customize my roadmap satisfactorily.

## Tasks
- [ ] Inspiration gathering
- [ ] Compile edge cases 
  - Eg: online florist, expanding businesses like Joey's mobile cigar lounge
  - Long-haul trucking
- [ ] Discuss with Jess
  - [ ] Share inspiration
  - [ ] Finalize list of edge cases
  - [ ] Questions
    - [ ] What about industries that aren't included? Do we have access to [these starter kit](https://business.nj.gov/starter-kits/more-kits-comings-soon) requests?
    - [x] Multi-select? Not yet
    - [x] Edge cases: what are the most complicated industry selections we can think of? We're continuing to build this list
    - [x] Will this consolidate Industry and Industry Sector? (it better) Not yet
- [ ] Design
  - [ ] Actual search
  - [ ] Wording for dropdown (eg "What is the purpose of your industry?" "what is your primary industry?") & follow-up questions to clarify (see longhaul trucking example)
  - [ ] Feedback: "we think your industry is retail" with contextual menu (what industry is, what it entails)
  - [ ] Multiple industry selection
  - [ ] Industry follow-up questions
  - [ ] "Don't see your industry? Suggest one here."
- [ ] Testing
  - [ ] Word mapping activity?
- [ ] Evaluation Plan
  - [ ] GA: searches with no results

## Initial Design Ideas
1. Synonyms
  - exploration of rethinking Industry drop down UX to make it clearer to users that their synonym falls under one of our Industries 
3. Licenses for an industry
4. Industry-specific onboarding question (below industry dropdown)

## Considerations / Challenges
1. Challenge scrolling and finding your industry (if not using the search), because too many industries with a smaller view
2. Challenge affirming to the user the industry they typed in and the industry we recommend are a match i.e. user types florist but we show them retail, how can we affirm to that user that that's the right choice
3. Challenge where the user might type in logistics but might be talking about long haul trucking, what is the ux experience for the user - do we ask a follow-up question to clarify their businesses primary purpose? If they sat logistics but with our questions we realize they are a really talking bout what we call trucking, do we correct them, or let them call themselves logistics, and, just show them the right tasks
5. Some industries have multiple industry specific follow-up questions, what is the right design for this
**Item 3 and 4 are talking about a new paradigm where industry selection doesn't map to one roadmap, it has nuance where multiple different task screens might display

## Notes
- [BFS Industry Flowchart](https://miro.com/app/board/uXjVO9feGK0=/)
- Final list will contain approximately 100 industries
- Also see #2577 
- Future iteration dependent on TBD dev spike: "investigate enabling industry-specific questions in onboarding for all industries via content editors"

**Comment by carye3** [comment]
https://docs.google.com/spreadsheets/d/1AV2uhETfVCzUIESv83qpN3VWbIqYtDGs6TZuReXRPYw/edit#gid=0
