### ISSUE TITLE
Add New Funding Opportunity Fields in Netlify

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#3038]
As a Content Administrator, I need the ability to manage new fields via Netlify so that I can work more efficiently.

## Acceptance Criteria
- [x] **Add "Program Purpose" field to funding programs**
- Retention
- Attraction
- Action Related Reward

- [x] **Add New Values to Agency field**
- update to multi-select dropdown
  - NJDEP
  - NJ Department of Treasury
  - NJ Board of Public Utilities

- [x] **Add Contact field**
- Input field (text)

- [x] **Separate File Name and URL fields**
- Split File Name and URL fields into separate fields
- Editable
- Netlify only

- [x] **Update Funding export for the new fields**

## Additional Acceptance Criteria
- 508 Compliant
- Follows Design
- Works in Mobile

## Approvals
- [ ] Content Review
- [ ] PO Approval

**Comment by dsueltenfuss** [comment]
@aaronvux  this is ready for review

**Comment by aaronvux** [comment]
@CeciliaRam @Jesslax please review

**Comment by CeciliaRam** [comment]
@aaronvux looks good, works perfect. 
didn't think this last AC item was for us: "Update Funding export for the new fields," but flagging it just in case bc I'm not sure how to check for that

**Comment by dsueltenfuss** [comment]
@CeciliaRam That last AC was for the dev team, to make sure we added the new fields to the manual export we run for Jess
