### ISSUE TITLE
Design: Exploration of Navigator Landing Page update that sets better user expectations about what the Navigator will provide

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#309]
When someone lands on the Navigator landing page, they don't know what exactly the Navigator will offer them. Can we add an example roadmap to the Navigator landing page, so people can better visualize how the Navigator will help them.

## Tasks

- [ ] Desk research / review previous research
- [ ] Design Exploration:
  - [ ] Explore Info wizard / walkthrough on landing page
  - [ ] Updating the landing page for navigator with more specific functionality
  - [ ] Testimonials
- [ ] Testing
- [ ] Final Designs

**Comment by skeeJay** [comment]
@Jesslax Not sure what this refers to. What who will get from the Navigator? Are you thinking that this applies to a specific screen?

**Comment by Jesslax** [comment]
@skeeJay Apologies, I updated the description a bit to answer your question. When Guy developed the designs for the landing page, in one of the reviews, Anne pointed out that it still wasn't very clear what people would get out of the Navigator, and we agreed it might help to add an example of the roadmap on the landing page. Due to time, it was not added in that first iteration. Beyond that, this need was confirmed in the user testing as 2 of the folks said that the landing page could better show what they will get from engaging with the Navigator. Hope that answers your question.

**Comment by skeeJay** [comment]
@Jesslax Okay, thanks, I updated the title to clarify.
