### ISSUE TITLE
Discovery: Social Media Ad Targeting Strategy for User Research

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#3243]
As a discovery team, we need consistent, reliable user research pipeline for specific persona groups in order to create content and design for those users.

1 month trial run testing LinkedIn and Facebook for a TBD persona group simultaneously, after which we will assess which targeting is most effective. To begin around 2nd week of July.

## Tasks
- [ ] Create ad design (in both facebook and linkedin)
- [ ] Write essential and non-essential screener questions
- [ ] Determine process: which screeners are delegated to targeting & in-platform screener forms vs an Airtable screener
- [ ] Launch Facebook & Linkedin simultaneously

## Ad Design (in both facebook and linkedin)
- Flexible to any of our personas
- Follow our branding
- Clearly gov’t site
- $75 gift card… or compensation
- Confidential / private / anonymized
- Online

## Notes
https://docs.google.com/document/d/17O4Im2JozL7PnHUu1o0QP-l0l1D7DrWUxDpksrbsTZU/edit#

**Comment by carye3** [comment]
@Jesslax feel free to add anything you think might be missing
