### ISSUE TITLE
User Research & Design: Oscar Experience Pt. 1&2

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#431]
Story: Oscar needs an onboarding flow tailored to their unique circumstances.

## Open Questions

- [ ] Sole proprietorships don't have Entity ID's. What shows in operate for them?

**Part 1**
- [x] Desk Research
- [x] Research Planning

**Part 2**
- [x] User Research: Card Sorts
- [x] Synthesis

**Part 3**
- [ ] Design
- [ ] Research planning
- [ ] Testing

**Part 3**
- [ ] Hi-fi testing / prototype
- [ ] Story mapping
- [ ] User flow mapping

**Part 2**
- [ ] What changes for Poppy etc once we roll out these changes?

Oscar needs an onboarding flow tailored to their unique circumstances

Oscar needs a dashboard of managing their business with filings, etc.

Oscar has functions and changes they can address as an operating business:

1. Register your business for tax and employer purposes
2. Change your registered agent/office
3. Amend your certificate of formation, incorporation or authorization
4. Request a Business Registration Certificate
5. Register for PBS (not sure if that is the same as item 1 on this list)
6. Change your tax registration account information online – for example, add or cancel a tax filing obligation (also available via PBS)

**Comment by carye3** [comment]
Initial comment from @Jesslax :

And now my thinking goes further, would an operate business get any of the same onboarding questions? Probably not. I think the first question needs to be, is your business in operation. If the answer is no, everything is as normal. If the answer is yes, the rest of the onboarding questions are not important. But we would need to ask new operate information to process and identify their files with treasury
