### ISSUE TITLE
BAC Service Design: Schedule Interviews

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#4576]
## Tasks
- [ ] Finalize outreach language in the [Research Plan](https://docs.google.com/document/d/1UEedP5c3mvT0LYF4VPILD5Di8_eUsCHeyXhqogVm9vM/edit)
- [ ] Conduct Kickoff mtg to review & begin scheduling (outreach led by @dltinnovate)

### Resources
- [Research Plan](https://docs.google.com/document/d/1UEedP5c3mvT0LYF4VPILD5Di8_eUsCHeyXhqogVm9vM/edit)
- [Chat/Bug audit 8/2/22](https://docs.google.com/spreadsheets/d/1XKtCBShRQugYlDJ4N1otscTMn9-Ao1deBC39OX-GoRE/edit#gid=0)

### Problem Statement
Responses from the BAC via chat to users regarding the Navigator are not providing the best support in the use of the Navigator. As measured by reviewing chats where users were routed from the Navigator to the BAC chat, and the qualitative analysis of the poor responses, which can cause users to abandon the Navigator and registration.  

### Business Objective
Equip the BAC to handle most Navigator related chat inputs. 

### Assumptions:
- Lack of context regarding questions about the Navigator vs. something else
- Lack of Knowledge about the features of the Navigator

BAC users using intercom to find issue or report bug.

Improving BAC technical customer service

## Ideation:
- [ ] Desk research: 
  - Meeting with Jess & Joe. Jess' research, some chat analysis in intercom. 
- [ ] Create service blueprint draft
- [ ] Create research plan
- [ ] Scheduling BAC interviews
