### ISSUE TITLE
B.NJ: Navigator Promotion

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#4577]
### Problem Statement: 
Users come to business.nj.gov to accomplish specific activities - register their in-state-business, out-of-state business, understand their tax obligations, find funding--the Navigator would provide better support than the website and users need to know that value proposition
...
Benefits Hypothesis: Upon increasing the promotion of the Navigator across the biz.nj.gov website, the daily use of the Navigator will increase.

Scope:
- Systematize how the Navigator is promoted across business.NJ.gov 
- Validate the three types of collateral - how can we improve each?
 - Top-line daily users of biz.nj.gov (about 3000), Navigator daily users (about 300) - increase of conversion?
- Create promotional material that can speak to diverse user goals
- Pages to include:
- landing page, starter kit, register your business, register for taxes, taxes and annual report, MWBE, SBE, VOB and Other Certifications, licensing-and-certification-guide 
- Leverage of the new landing page query strings
- some pages need enhancements, and some need collateral for the first time 
- Leverage google optimize - test copy and design

### Draft user stories
- New Sub-page
  -- As a Biz.nj.gov user, I want to easily act on my intentions to create my personalized business roadmap so that I can get started on my business journey using the Navigator.  
  -- AC: On the <> page, then 'Get Started' left navigation appear that redirects to the Navigator
  -- AC: On the <> page, then 'Registering your business?' pill appears above the fold
- Industry Starter Kits
  -- As a Biz.nj.gov user, I want to easily act on my intentions to start my business for a particular industry so that I can get started on my business journey using the Navigator.
- More stories for all the templates?

### Actions & Outcomes:
- [x] Review existing Navigator promo collateral
- [x] Ideation
  - [x] How can we address all use cases (listed above):
    - [x] Location of promo elements
    - [x] What kind of promo elements we're using 
- [x] Market research
- [ ] Design
  - [ ] Homepage
  - [x] Starter Kits
  - [x] Sub-Pages
    - [ ] register your business
    - [ ] register for taxes
    - [ ] taxes and annual report
    - [ ] MWBE, SBE, VOB and Other Certifications
  - [ ] Updates
  - [ ] Funding
  - [ ] Licenses & Certs
  - [ ] Search Results
- [ ] Design Review
- [ ] Prep for Testing
  - [ ] Mini-Content Review
- [ ] Test improvements and provide recommendations for implementation
- [ ] Review for accessibility
- [ ] Design Review (dev)
  - [ ] Discuss whether to have generic or custom copy for hero button
- [ ] Google Analytics discussion
- [ ] Clean up Figma files and update Page status 
  - [ ] Include tab order

Goal:
Increase Navigator link clicks across Business.NJ.gov

Ideation:

https://app.mural.co/t/officeofinnovation7132/m/officeofinnovation7132/1658244433065/c88facbfbc669d46ed0835ccd089136a124905fa?sender=ue10ab572e1cfe32fb3df1678
