### ISSUE TITLE
Current Sprint - Dev:Design Pairing (Dev QA)

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#607]
[StoryBook Link](http://nj-bfs-design-storybook.s3-website-us-east-1.amazonaws.com/?path=/story/designsystem--colors)

### Colors
- [ ] Add colors from Oscar Dashboard tags
- [ ] [Add hover state for chips](http://nj-bfs-design-storybook.s3-website-us-east-1.amazonaws.com/?path=/story/components-tag--hover)
- [ ] revisit colors on the license-status component - using new colors / not in design system

### Task for Dev
- [ ] Replace Button component with dynamic Button component

**Comment by carye3** [comment]
508 tab selection & field error 

![image](https://user-images.githubusercontent.com/62653834/136589782-e80678ab-12ed-4678-9764-0883550dd393.png)
Faraz: I think it would be helpful if we created components based on MUI TextField component in different states (i.e. error, with icon, with focus, helper text etc) within Figma & potentially utilize them across designs in a consistent manner.
With the components layed out, I think we should be able to create a consistent theme that overrides current styling. Note: in some areas of the app, we may not be using the MUI TextField and will need to create bugs in GitHub to address the issue at a future time.

**Comment by carye3** [comment]
@fiorella-io

**Comment by carye3** [comment]
Faraz increased padding beween fields and descriptor text to 10px universally
