### ISSUE TITLE
Homepage (Hi-Fi & Mobile)

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#637]
## Tasks
- [x] "Featured Industry Starter Kits", A to Z
- [x] What's New: fix tile color, include "Visit our new Funding Page!"
- [x] Topics: differentiate Start & Operate colors
- [x] Remove funding from nav at top (ALL PAGES)
- [x] Fund icon -- apply everywhere
- [x] 3 Options (Different icons for V2,3)
- [x] Design Review: Includes Homepage
- [x] User Test 1: Hompeage only (2 options)
- [x] User Test 2: Homepage and maybe more (2 options)
- [x] Accessibility expert needed
- [x] Hover state: need to check with accessiblity folks at fearless. might need to change to click
- [x] Jess: where are results of card sorting (business stages)?
- [x] Simplify icons for responsiveness
  - [x] Plan (flags?)
  - [x] Grow
  - [x] Funding
  - [x] Updates
 - [x] Experiment with alternate blueish green

**Future/Testing**
- [x] Having search bar in hero image
