### ISSUE TITLE
Updates (Hi-Fi & Mobile)

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#639]
## All Tasks
- [x] "Latest" Section at the top with an overview of all pages (with labels)
- [x] Expandable tile 
- [x] New icon
- [x] Re-consolidate Grants & Resources

## Tasks for Demo (10.28.21)

- [x] Remove from COVID: Recent Guidance, biz restrictions, Remove biz reousreces and financing. Keep economic assistance

Open Questions:

- Jess/Joe: where do resources go after several months have passed?
