### ISSUE TITLE
Biz.NJ Homepage: Update Hero Image & Functionality

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#650]
As a NJ Business Owner, I need the ability to easily search and find information on business.nj.gov homepage so that I can get critical information for my business.

## Acceptance criteria

Add the following items to the hero image on business.nj.gov homepage:

- Slogan
- Search Bar
- Editable Pill Buttons with icons and text
  - Ask an Expert (opens intercom)
  - 1-800-Jersey-7 (unclickable)
  - COVID-19 (opens accordion on the updates page within the same tab)
  - Newsletter
- Follows Design
- 508 Compliant

## Designs
[Homepage: Desktop](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6205%3A75320)
![image](https://user-images.githubusercontent.com/62653834/139755056-3bcf4165-4570-48e7-b09c-4bb1f74919da.png)

[Homepage: Mobile](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6205%3A75326)
![image](https://user-images.githubusercontent.com/62653834/139755099-1fd9f9ea-ed7b-470b-9b9e-85bf9c3dd1a4.png)

## Notes

- [ ] UX Review
- [ ] PO Approval

**Comment by carye3** [comment]
@fiorella-io @aaronvux please review when you get a moment -- thx

**Comment by dltinnovate** [comment]
@aaronvux 
resolved, ready for QA

- [x] Slogan
- [x] Search Bar
- [x] Editable Pill Buttons with icons and text
- [x] Ask an Expert (opens intercom)
- [x] 1-800-Jersey-7 (unclickable)
- [x] COVID-19 (opens accordion on the updates page within the same tab)
- [x] Newsletter
- [x] Follows Design
- [x] 508 Compliant

Additions

- [ ] Need to source two more default "business owner" images for slider

**Comment by aaronvux** [comment]
This is done.  Sending Joe two images for the carousel.
