### ISSUE TITLE
Biz.NJ Homepage: Plan, Start, Operate, Grow

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#651]
As a NJ Business Owner, I need to have an experience more inline with the Navigator application so that I can easily manage my business.

## Acceptance criteria
- Remove existing Build Your Capacity section on home page of business.nj.gov
- Replace with We're here for any part of your journey section.
  - Implement Plan, Start, Operate, Grow (4 column grid)
  - Edit pill buttons (text only)
  - View Contents button navigates user in same to Topics page
  - Hover state reveals nav menu.  Still need to figure out mobile.
 
## Designs
[Homepage: Desktop](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6205%3A75320)
![image](https://user-images.githubusercontent.com/62653834/139758958-93a0a0cd-2a26-4751-a211-c77904cb4046.png)

[Homepage: Mobile](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6205%3A75326)
![image](https://user-images.githubusercontent.com/62653834/139758940-7ce36935-d283-4ed7-a694-6fa20da3f740.png)

## Notes

- [ ] UX Review
- [ ] PO Approval

**Comment by carye3** [comment]
@fiorella-io @aaronvux please review when you get a moment -- thx

**Comment by carye3** [comment]
Discussed with @dltinnovate and @fiorella-io -- on mobile, tapping the P/S/O/G tiles will bring up nav menu, expanding an accordion for that topic (instead of navigating to the topics page)

**Comment by dltinnovate** [comment]
@aaronvux 

- [x] Remove existing Build Your Capacity section on home page of business.nj.gov
- [x] Replace with We're here for any part of your journey section.
- [x] Implement Plan, Start, Operate, Grow (4 column grid)
- [x] Edit pill buttons (text only)
- [ ] View Contents button navigates user in same to Topics page **NOTES: Need to build our hover state that displays clickable content pages for that topic.**
- [ ] Hover state reveals nav menu. Still need to figure out mobile. **NOTES: Needs to be built for desktop. Mobile still needs a design.**

**Comment by aaronvux** [comment]
Splitting these two items to a new ticket.  This ticket is otherwise complete.

 View Contents button navigates user in same to Topics page NOTES: Need to build our hover state that displays clickable content pages for that topic.
 Hover state reveals nav menu. Still need to figure out mobile. NOTES: Needs to be built for desktop. Mobile still needs a design.
