### ISSUE TITLE
Biz.NJ Homepage: Top Content

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#652]
As a NJ Business Owner, I need the ability to view new information that pertains to my business so that I can make well informed decisions.

## Acceptance criteria

- Create What's New section on Home page
- Tiled content boxes with horizontal scrolling and left/right chevrons. 
  - Horizontal-scrolling tiles with scroll-right chevron advancing 3 tiles. Hide left-scroll chevron; upon scrolling right, display left-scroll chevron.
  - Each tile should include content from different topics from business.nj.gov (content is TBD)
  - Ranked ordering of tiles
  - Corresponding icons & color coding to the linked content - Includes Navigator promotional tile
- CMS:
  - Create toggle to add any content to the What's New section
  - Ability to specify rank / order of tiles
- 10-tile limit.

## Designs
[Homepage: Desktop](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6126%3A68820)
![image](https://user-images.githubusercontent.com/62653834/139762898-2da23f79-c9a9-48e2-a07f-3ff2ed0addad.png)

[Homepage: Mobile](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6126%3A68946)
![image](https://user-images.githubusercontent.com/62653834/139762692-0c633c0f-5abf-491a-a056-70f665252144.png)

## Notes

- [ ] UX Review
- [ ] PO Approval

**Comment by carye3** [comment]
@fiorella-io @aaronvux please review when you get a moment -- thx

**Comment by dltinnovate** [comment]
@aaronvux
First iteration ready

Create What's New section on Home page
Tiled content boxes with horizontal scrolling and left/right chevrons.

- [x] Horizontal-scrolling tiles with scroll-right chevron advancing **4 tiles (not three)**. Hide left-scroll chevron; upon scrolling right, display left-scroll chevron.
- [x] Each tile should include content from different topics from business.nj.gov (content is TBD)
- [x] Ranked ordering of tiles
- [x] Corresponding icons & color coding to the linked content - Includes Navigator promotional tile

CMS: **NOTES: currently only linked to GENERAL CONTENT CMS can manually add unique content items at the beginning or end. Next iteration we'll need to built integration with COVID and Updates CMS**

- [ ] Create toggle to add any content to the What's New section
- [ ] Ability to specify rank / order of tiles

- [x] 10-tile limit.
