### ISSUE TITLE
Create new personas and update epics

### ISSUE THREAD

**Issue by Jesslax** [newjersey/navigator.business.nj.gov#676]
## Action Items
- [ ] Rearrange [personas](https://airtable.com/appn2D7J0Tzt2HNCu/tblhr4RLxnk2M23l9/viwrgDbyzVoaWWQqE?blocks=hide) by archetype, demographic info, and journey
- [ ] Share with research teams at Fearless / Coforma for feedback
- [ ] Incorporate feedback and share with Jess, V, Neha
- [ ] Update persona table and incorporate into research repository, github

## Misc
Add accountants and lawyers

**Comment by skeeJay** [comment]
Action item is to @carye3 to organize. cc @kmelefsky
