### ISSUE TITLE
Display Spinner/Loading Feedback when pages are being loaded/saved

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#705]
As a business owner,  I need the Navigator to display spinner/loading feedback when pages are loaded or saved so that I know that the system is working on my request.

## Acceptance criteria

- Display a spinner/loading feedback anytime a page is being loaded or saved until the page is fully loaded or saved.
- Works in mobile
- 508 Compliant

## Tasks
- [x] Create CTA spinner
- [ ] Catalogue asyncronous calls
- [x] Create "next button" spinner

## Design
[CTA Button Spinner](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=5815%3A111979)

[Next/Previous Button Spinner](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=5842%3A106753)

## Notes

- [ ] UX Review
- [ ] PO Approval

**Comment by aaronvux** [comment]
@kmelefsky let's discuss this one on Monday at 16th minute please.

**Comment by aaronvux** [comment]
Discussed this story today.  Moving to archives.
