### ISSUE TITLE
Roll out Navigator/invite users

### ISSUE THREAD

**Issue by skeeJay** [newjersey/navigator.business.nj.gov#731]
**As** <PERSONA>
**I need to** <GOAL>
**So that** <OUTCOME>

## Acceptance criteria

- Create Role Description for CBO user research pipeline.

## Tasks

- [x] Talk to Kai about options 
  - [ ] Working through agency partners (BAC) / SBDCs to market Navigator
  - [x] Advertise directly on Biz.NJ
  - [ ] Targeted user onboarding by BFS in tandem with user testing
  - [x] send out a newsletter article this week framing the Navigator as a product for new businesses only
  - [x] discuss with other agency comms ideas for promoting the Navigator
  - [ ] create social media collateral for other agencies to share
  - [ ] create draft e-blast for LAEDA to send
  - [ ] Give demo to librarian group Dec 16th
  - [ ] Continue to identify organizations that have the right target audience (new businesses) that can cross-promote the Navigator
  - [ ] Have Katie support with marketing plan
  - [ ] Place targeted ads/google?
  - [ ] Timeline (slow 40-50 over next 2-3 weeks / 25 a week)
- [ ] Finalize strategy / roadmap
  - [ ] User Feedback: Interviews, Surveys (10+ users)

## Notes
- [ ] Slow rollout: # of users a week 
   - [ ] BAC/SBDC's engage users - procedure for rollout, language / outreach documents, and maybe surveys
- [ ] Or wider exposure: link on biz.nj, or newsletter blast 
  - [ ] Start with our own
  - [ ] Talk to SBDC, give them a demo and ask them to do direct outreach
  - [ ] Newsletter via LAEDA

E.J.'S NOTES
PHASE 1
- Ask BAC to start sharing
- Put link on Business.NJ.gov
    - - Put at the top of white section of register
    - - Put modal on register

PHASE 2
- Our newsletter

PHASE 3
- Email newsletter blast from LAIDA
- Libraries
- Road show

**Comment by skeeJay** [comment]
We have rolled out the first links on B.NJ.gov. In a few days we should have a conversation about next steps.

**Comment by skeeJay** [comment]
Happening in Newsletter this week as next step.

**Comment by kmelefsky** [comment]
@Jesslax to update checklist

**Comment by Jesslax** [comment]
updated the checklist
