### ISSUE TITLE
BFS Design System

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#737]
As the development team, I need access to a design system for BFS products (Navigator & Biz.NJ) so that all assets designed or implemented are consistent across all products in look and accessibility compliance.

## Design System Files
[BFS Design System](https://www.figma.com/file/ajJHQnGGrEAOXmY3CXdFKn/BFS-Design-System?node-id=0%3A1) (based on NJWDS, USDWS, and Material UI)

## Tasks
- [ ] Inconsistencies Audit:
  - [ ] Take screenshots of inconsistencies
  - [ ] Do a few hour long audit sessions per sprint in Storybook
  - [ ] Update components / create tickets for new components afterward
  - [ ] For when new designer is onboarded
- [x] #1537
- [x] #2039
- [ ] Update spacing of Back and Save button on Profile edit page when a button is focused. -> global change, default is margin-right: 1rem, changing to 2rem (16px)
- [x] https://github.com/newjersey/navigator.business.nj.gov/issues/1430
- [ ] Header tagging, introducing new H2/H3 tag
- [ ] Remove Step 2 from Plan in all screens
- [ ] Use naming conventions similar to USWDS - CSS Utilities [designsystem.digital.gov/utiliites/colro](http://designsystem.digital.gov/utiliites/colro)
- [ ] Update design system using assets from:
  - [ ] Biz.NJ redesign
  - [ ] Navigator file (latest design)
  - [ ] Material UI being used on Navigator (eg Accordions, snackbars)
  - [ ] USWDS where applicable (eg modals)
- [ ] Componentize assets, including various states
- [ ] Include Noun Project codes
- [ ] Contrast check / accessibility review
- [ ] Iterate with Faraz / dev team during dev:design pairings
- [ ] Desktop version is Tablet-friendly (when tablet users become critical segment of users)

## Optional
- [ ] Back button for contextual menu?
