### ISSUE TITLE
Biz.NJ: Nav, Alert Bars & Dropdown

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#814]
## Acceptance Criteria

General:
- [ ] Alert banner follows guidelines (see Jess' document) and opens updates page for that particular alert
- [ ] Business.NJ logo opens homepage
- [ ] 508 Compliant
- [ ] Follows design

Desktop Nav Bar:
- [ ] Search bar
  - [ ] Not displayed on Homepage
- [ ] Dropdown menus for Topics and Updates
- [ ] Updates:
  - [ ] Includes icon with 2 versions: (1) with notification dot, (2) without
- [ ] Chat opens Intercom 

Mobile Hamburger Menu:
- [ ] Hamburger menu
- [ ] Search opens search page
- [ ] Ask an Expert opens intercom
- [ ] All topics opens Topic Landing Page
- [ ] Tapping each topic opens topic sub-menu

## Designs

[Homepage: Desktop](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6205%3A75320)
![image](https://user-images.githubusercontent.com/62653834/139755430-88e5eef7-92c7-48dd-8fda-aee1e1ad497e.png)

[Homepage: Mobile](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6205%3A75326)
![image](https://user-images.githubusercontent.com/62653834/139755472-9ad60feb-3481-4ab5-8f45-5cff4982186e.png)

[General Nav: Desktop](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6209%3A73595)
![image](https://user-images.githubusercontent.com/62653834/139755594-a242d2af-98d4-4f35-83c0-a2077252e5ae.png)

[General Nav: Mobile](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6209%3A73596)
![image](https://user-images.githubusercontent.com/62653834/139755627-08c54060-7aba-409f-86c6-974f56cdb983.png)

[General Nav - Dropdown: Desktop](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6205%3A76800)
![image](https://user-images.githubusercontent.com/62653834/139757000-ce8b74e4-e979-4a21-95b8-e23311a51f38.png)

[General Nav - Hamburger Menu Main: Mobile](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6224%3A75027)
![image](https://user-images.githubusercontent.com/62653834/139757168-6d7f89ae-bb9d-453b-ac64-3ed13c551766.png)

[General Nav - Hamburger Menu Sub-Menu: Mobile](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6224%3A75026)
![image](https://user-images.githubusercontent.com/62653834/139757235-646ac86a-4e2c-43c8-ae80-d4266353004d.png)

**Comment by dltinnovate** [comment]
@aaronvux 

General:

- [ ]  Alert banner follows guidelines (see Jess' document) and opens updates page for that particular alert **NOTES: need to fix this to work with automatic section scrolling. Current iteration pushes down nav and hides section title. Working to fix this week of 12/13.**
- [x]  Business.NJ logo opens homepage
- [x]  508 Compliant
- [x]  Follows design

Desktop Nav Bar:

 Search bar

- [x]  Not displayed on Homepage
- [x]  Dropdown menus for Topics and Updates

 Updates:

- [x]  Includes icon with 2 versions: (1) with notification dot, (2) without **NOTES: manually controlled**. We must show or hide the dot dependent on if there's news that needs to be highlighted or not.
- [x]  Chat opens Intercom

Mobile Hamburger Menu:

- [x]  Hamburger menu- switches between hamburger and close button for menu
- [x]  Search opens search page NOTES: have an iteration that keeps the search box. Don't know that we want to hide this behind two clicks.
- [x]  Ask an Expert opens intercom
- [x]  All topics opens Topic Landing Page
- [x]  Tapping each topic opens topic sub-menu
   - [ ] matches background color of topic. **NOTES: trickier implementation and might need to rebuilt to get this to work. Recommend for next iteration**

**Comment by dltinnovate** [comment]
@kmelefsky We can close this. We should create a ticket for the next iteration to create a custom sub-menu for each category in the mobile menu.

**Comment by kmelefsky** [comment]
@dltinnovate will go ahead and close this one, i just created a placeholder ticket for the next iteration which is now in the icebox, #1389
