### ISSUE TITLE
Content + Design: Research Business Requirements for new Business Formation in the Navigator 

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#825]
As Poppy, I need to the ability to submit and pay for all of my Business Formation Filings on the Navigator so my business can be in compliance with the State of NJ quickly and easily.

## Tasks

- [ ] Design
  - [ ] Submission button / error message
  - [ ] Payment success/failure (after 3 tries) messages
- [ ] Research
  - [ ] What fields are required?
- [ ] Content
  - [ ] "Provisions" renamed (Additional Content?)

**Comment by aaronvux** [comment]
Business Formation research and designs are the priority over Oscar dashboard research and design.

**Comment by Jesslax** [comment]
We are waiting on some final answers on members, disclaimer, and signatory.

**Comment by kmelefsky** [comment]
@Jesslax  and @carye3 do we have any update on this story? thx!
