### ISSUE TITLE
Biz.NJ: Topics Landing Page

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#845]
## Acceptance Criteria

- [ ] Desktop: 
  - [ ] Follows designs with large outlined icon aligned left of header text
  - [ ] Horizontal-scrolling tiles with scroll-right chevron advancing 3 tiles. Upon scrolling right, display left-scroll chevron
- [ ] Mobile:
  - [ ] Follows designs: small solid icon left aligned above header text
- [ ] Navigating from homepage  topics section and navigation menu will scroll to location of that topic on page
- [ ] 508 Compliant
- [ ] Follows Designs

## Acceptance Criteria

[Desktop](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6205%3A77873)
![image](https://user-images.githubusercontent.com/62653834/139926963-f4ea988a-2fd9-4c49-80af-37b68145fa5c.png)

[Mobile](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6205%3A77874)
![image](https://user-images.githubusercontent.com/62653834/139927030-cfeed336-4a80-4777-b1ae-839e699e74ca.png)

**Comment by carye3** [comment]
@fiorella-io @aaronvux please review when you get a moment -- thx

**Comment by dltinnovate** [comment]
@mikewolfd is investigating a work-around to display mobile sliders as intended. We have developed an alternative design in case it's not possible.

**Comment by dltinnovate** [comment]
@aaronvux  
Desktop:
- [x] Follows designs with large outlined icon aligned left of header text
- [x]  Horizontal-scrolling tiles with scroll-right chevron advancing 3 tiles. Upon scrolling right, display left-scroll chevron (NOTE: Advances by 4 at a time instead of three.)
 
Mobile:
- [x] Follows designs: small solid icon left aligned above header text
- [ ] Need white mobile icons to finish mobile design (currently adapted to use desktop icons)
- [ ] Not able to have scrollable tiles on mobile, adapted to keeps tile format but display information in mobile friendly manner. Need approval.
