### ISSUE TITLE
Biz.NJ Topics Sub-Page: Top Banner

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#846]
## Acceptance Criteria

- [ ] Follows Designs
    - [ ] Create Illustration Banner
    - [ ] Add Icon, topic, title and description 
- [ ] Check 508 Compliance

## Design

[Desktop](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6209%3A73595)
![image](https://user-images.githubusercontent.com/62653834/139928123-a0ceb03b-aae2-484d-8652-8eee4a6a4266.png)

[Mobile](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6209%3A73596)
![image](https://user-images.githubusercontent.com/62653834/139928178-b37f3ecd-9330-458a-9220-484e758ea6de.png)

**Comment by carye3** [comment]
@fiorella-io  @aaronvux  please review when you get a moment -- thx

**Comment by dltinnovate** [comment]
@aaronvux 

Follows Designs
- [x]  Create Illustration Banner
- [x]  Add Icon, topic, title and description
- [x]  Check 508 Compliance
- [ ] Need white mobile icon

**Comment by dltinnovate** [comment]
@kmelefsky we can close this. Mobile icons are up and running
