### ISSUE TITLE
Biz.NJ Updates Page: Contents

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#851]
## Action items:

- [ ] Pair Graham (granicus access) with Mike to restyle the embedded newsletter signup button

## Acceptance Criteria

- [ ] Expandable tiles with date, blurb, read more, and Topic & Category tags
  - [ ] Tags: Topics are outlined, eg Hurricane Ida or COVID. Categories are solid, and describe types of information, eg grants and resources.
  - [ ] Clicking "read more" expands the tile, upon which a close X icon appears in upper right corner, and the "read more" text now appears as "view less"
  - [ ] Closed by default
- [ ] Floating "Back to Top" link below Intercom icon 
- [ ] Sign up for newsletter box displayed at bottom of content tiles
- [ ] Follow design
- [ ] 508 compliant

## Design

[Desktop](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6209%3A73595)
![image](https://user-images.githubusercontent.com/62653834/139928123-a0ceb03b-aae2-484d-8652-8eee4a6a4266.png)

[Mobile](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6209%3A73596)
![image](https://user-images.githubusercontent.com/62653834/139928178-b37f3ecd-9330-458a-9220-484e758ea6de.png)

**Comment by carye3** [comment]
@fiorella-io @aaronvux please review when you get a moment -- thx

**Comment by carye3** [comment]
@dltinnovate added action item for granicus:


"Pair Graham (granicus access) with Mike to restyle the embedded newsletter signup button"
