### ISSUE TITLE
Biz.NJ Fund Page: Banner etc

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#852]
## Action Items:
- [ ] Add “grow” above Funding in the banner
- [ ] Having sub-heading for industry type in the tile (design [here](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=5563%3A125323))
- [ ] Filter tags occupy full width of column (move total results above the line)
- [ ] Share new designs and then reformat tiles to have bulleted list and expand/collapse (design [here](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=5563%3A125323))

## Acceptance Criteria

- [ ] Follows design
    - [ ] Create Illustration Banner
    - [ ] Add Icon, title and description 
- [ ] 508 compliant

## Design

[Desktop](link)
![image](https://user-images.githubusercontent.com/62653834/139939689-a1ba9227-a185-4aaf-ab30-ee4e92b2179e.png)
https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6224%3A78402

[Mobile](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6222%3A76479)
![image](https://user-images.githubusercontent.com/62653834/139940031-98850047-f133-455f-ae9b-5489f19a4f15.png)

**Comment by carye3** [comment]
@fiorella-io @aaronvux please review when you get a moment -- thx

**Comment by carye3** [comment]
Action items updated above @dltinnovate

**Comment by dltinnovate** [comment]
- [x] Add “grow” above Funding in the banner
- [ ]  Having sub-heading for industry type in the tile (design here)
- [ ]  Filter tags occupy full width of column (move total results above the line)
- [ ] Share new designs and then reformat tiles to have bulleted list and expand/collapse (design here)

**Comment by Jesslax** [comment]
@dltinnovate @carye3 can we close this?

**Comment by dltinnovate** [comment]
@Jesslax  we should be able to close this. It was superseded when we married the funding page template with the Navigator funding database. We adjusted the design to match the Netlify format and generated individual funding pages for items listed in the updates section. @carye3 let me know if I'm missing anything.
