### ISSUE TITLE
Biz.NJ Fund Page: Contents

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#854]
## Acceptance Criteria

- [ ] Follows Design
- [ ] 508 Compliant
- [ ] Tiles
  - [ ] Limited to 7 per page
  - [ ] Heading links to application
  - [ ] Elibility links to certification applications / descriptions
  - [ ] Benefits describes dollar amount / range or similar
  - [ ] Tags auto-populate based on opening date (not displayed in tile) and deadline
    - [ ] Apply Soon: Application period has not yet opened
    - [ ] Apply Now: application period has opened, is not closed,
    - [ ] Closed: application period has closed

## Design

[Desktop](link)
![image](https://user-images.githubusercontent.com/62653834/139939689-a1ba9227-a185-4aaf-ab30-ee4e92b2179e.png)
https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6224%3A78402

[Mobile](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6222%3A76479)
![image](https://user-images.githubusercontent.com/62653834/139940031-98850047-f133-455f-ae9b-5489f19a4f15.png)

**Comment by carye3** [comment]
@fiorella-io @aaronvux please review when you get a moment -- thx
