### ISSUE TITLE
NPS Survey for Navigator Launch

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#909]
As a development team member, I need to rapidly gather feedback on the newly public Navigator in order to improve the user experience efficiently.

## Acceptance Criteria

- [ ] Displays above intercom button
- [ ] Display NPS survey after 7 minutes of usage of the Navigator (post-onboarding)
- [ ] After submitting NPS score, optionally solicit feedback and an email address. If the email address format is invalid, display error message on blur or on clicking submit button.
- [ ] Compile responses in an easily accessible format for BFS researchers
- [ ] 508 compliant
- [ ] Follows design

## Design

[NPS Screen 1 - Survey](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6021%3A109170)
![image](https://user-images.githubusercontent.com/62653834/140796669-a4f65c9c-796b-446f-ae3a-23e7ca98acd2.png)

[NPS Screen 2 - Additional Feedback](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6021%3A109731)
![image](https://user-images.githubusercontent.com/62653834/140796830-e7abd0d4-8e63-4d6b-a4d4-e6db82ac9aa0.png)

[NPS Screen 2 - Error](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6054%3A111487)
![image](https://user-images.githubusercontent.com/62653834/140796901-c7854b18-dad9-4bae-b92f-d30cef151654.png)

**Comment by carye3** [comment]
for your review @aaronvux might have missed an existing NPS survey ticket...

**Comment by carye3** [comment]
@dltinnovate is this in line with intercom functionality? and how is response data accessed?

**Comment by aaronvux** [comment]
I created a ticket on the discovery board, but can delete if we want to use this one @carye3 Should this stay on the sprint board?

**Comment by carye3** [comment]
ya i think it's ready to go once dev looks at it. content has been reviewed by Jess @aaronvux

**Comment by carye3** [comment]
@fiorella-io lmk if you have any thoughts

**Comment by dltinnovate** [comment]
@carye3 Intercom works as a chat conversation. We can implement something really simple without needing a third party app like the survey below.



https://user-images.githubusercontent.com/68555384/140808021-f439af2d-a4bf-4a3e-bdd3-d41f2d402647.mov

**Comment by dltinnovate** [comment]
The downside is that this doesn't have the best analytics. The path analysis just aggregates responses over time with no trend or time breakdowns. 

2. Another option is to use a third party tool like [Survicate](https://survicate.com/integrations/intercom/), however most of these services require an additional paid subscription.
![Screen Shot 2021-11-08 at 3 04 09 PM](https://user-images.githubusercontent.com/68555384/140810148-6e1fc4ed-77e0-4b31-b3b3-8f69135424fa.png)

3. Lastly, we could use a URL to link to a survey.

**Comment by aaronvux** [comment]
Need @dltinnovate input on this story.

**Comment by carye3** [comment]
@dltinnovate sounds like the intercom version would be easiest to implement quickly. so it sounds like analytics within intercom aren't so good but we can download survey response data and see trends over time?

**Comment by dltinnovate** [comment]
@carye3 that implementation is a hack using Intercoms built in path analysis. [Details here](https://www.intercom.com/help/en/articles/3473772-optimize-your-custom-bots-with-path-analysis). So in order to get time specific data we would have to manually start, stop, and reset the bot, to reset the data. So this is a quick and dirty implementation, that might be a good temporary solution until we get the testing/feedback software up and running.

**Comment by carye3** [comment]
ok thanks @dltinnovate 

@aaronvux it sounds like we can do this intercom as a temporary solution that Joe can get started on asap and then create a new / duplicate ticket for the dev team to develop in the next sprint?

**Comment by carye3** [comment]
@dltinnovate this is ready for you to implement (we agreed it could be a short-term solution that could be developed in the next sprint if you have time)
