### ISSUE TITLE
Navigator Heuristic Analysis

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#939]
- [ ] **Assessment**
  - [ ] Compile & review user feedback - Cary
  - [x] Review existing UX stories
  - [x] Heuristic evaluation of site (dev)
  - [x] Compile suggested features in a presentation of sorts... Fiorella
  - [ ] Share deck on Friday 11.12
