### ISSUE TITLE
NPS Popup Survey for Navigator Launch

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#949]
As a development team member, I need to rapidly gather feedback on the newly public Navigator in order to improve the user experience efficiently.

## Acceptance Criteria

- [ ] Displays above intercom button
- [ ] Display NPS survey after 7 minutes of usage of the Navigator (post-onboarding)
- [ ] After submitting NPS score, optionally solicit feedback and an email address. If the email address format is invalid, display error message on blur or on clicking submit button.
- [ ] Compile responses in an easily accessible format for BFS researchers
- [ ] 508 compliant
- [ ] Follows design

## Design

[NPS Screen 1 - Survey](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6021%3A109170)
![image](https://user-images.githubusercontent.com/62653834/140796669-a4f65c9c-796b-446f-ae3a-23e7ca98acd2.png)

[NPS Screen 2 - Additional Feedback](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6021%3A109731)
![image](https://user-images.githubusercontent.com/62653834/140796830-e7abd0d4-8e63-4d6b-a4d4-e6db82ac9aa0.png)

[NPS Screen 2 - Error](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6054%3A111487)
![image](https://user-images.githubusercontent.com/62653834/140796901-c7854b18-dad9-4bae-b92f-d30cef151654.png)

**Comment by carye3** [comment]
Discussed during planning 11.10.21 that we will do an intercom version via Joe in the short term, and then develop OR build through JotForm/ other 3rd party software as next step (tentatively putting into sprint 24)

**Comment by aaronvux** [comment]
@dltinnovate does this still need to be implemented?  Can't remember if I saw in Slack that this was already live.

**Comment by dltinnovate** [comment]
@aaronvux the Intercom survey is up and running! We got approval on the wording and the James Gandolfini meme from the front office and went live last week.

**Comment by aaronvux** [comment]
@carye3 @fiorella-io please review

**Comment by carye3** [comment]
It looks like the acceptance criteria changes -- it shouldn't take 7 minutes to show. Do we have the original acceptance criteria documented?

**Comment by dltinnovate** [comment]
The current Intercom implementation displays after a user spends 60 seconds on any single task screen.

**Comment by aaronvux** [comment]
> It looks like the acceptance criteria changes -- it shouldn't take 7 minutes to show. Do we have the original acceptance criteria documented?

I don't think we can see history in Github unfortunately.

**Comment by carye3** [comment]
I'm on navigator.business.nj.gov and its not showing for me yet after 60 seconds @dltinnovate 

is it working for you @aaronvux ?

**Comment by aaronvux** [comment]
Not seeing it either. @dltinnovate

**Comment by aaronvux** [comment]
Still not seeing this consistently in Production.  Received the general popup when I was in Incognito after 60 seconds on task, but not the survey.  @dltinnovate will create an exception for this to see if it resolves the issue and allows the survey to pop-up.

**Comment by dltinnovate** [comment]
I've created the exception so the general popup doesn't walk on the survey. Feel free to test again.

**Comment by aaronvux** [comment]
Still not seeing the popup.  Tried with a different computer.  Attached screen capture. @dltinnovate 

https://user-images.githubusercontent.com/36163601/144615371-bd8575cb-fe4b-41d5-81fe-174a3343bb6b.mov

**Comment by aaronvux** [comment]
@dltinnovate clearing my browsing content did not display the popup.  I also created a new account and tested in a Safari, but the popup did not display.
