### ISSUE TITLE
Business Formation V1 (LLC)

### ISSUE THREAD

**Issue by aaronvux** [newjersey/navigator.business.nj.gov#977]
As Poppy with an LLC Business, I need the ability to submit all of my business formation information through the Navigator so I can easily complete what is required of me to form my business with the state of NJ from a single portal.

**THIS STORY IS DEPENDENT ON THE NIC API**

## Acceptance criteria

- Incorporate into "Form Your Business Entity" task.
- Use the Business Formation Test Endpoint
- Users will navigate between the steps with back and continue buttons.
- Specially designated fields will be pre-populated with available information from the Profile. 
- Editing specially designated fields will send the user to the Profile page to make any updates.
- If LLC is the Business Structure, the user will receive the new Business Formation workflow in the Form Your Business Task.
- For any email address that is required by the API, use the email address from the user's Navigator profile.
- Use existing UX patterns for inline validations for input fields and success/errors banners for API submission.

## Form Fields
------------------

- [x] - Business Structure (static display from Profile) (required)
- [x] -- Edit Link sends the user back to the Profile Page
- [x] - Business Name (static display from Profile)(required)
- [x] -- Edit Link sends the user back to the Business Name Search page.
- [x] - Business Suffix (required)
- [x] -- Dropdown
--- LLC
--- L.L.C.
--- LTD LIABILITY CO
--- LTD LIABILITY CO.
--- LTD LIABILITY COMPANY
--- LIMITED LIABILITY CO
--- LIMITED LIABILITY CO.
--- LIMITED LIABILITY COMPANY
- [x] - Business Start Date (required) 
- [x] -- Use Existing Date Picker
- [x] -- Default to Today's Date
- [x] -- Can only accept Today's Date or Future Dates

------------------
- [x] - Main Business Address (section title)
- [x] - Address Line1 (required)
- [x] - Address Line 2
- [x] - City (required)(static display from Profile)
-- Edit Link sends the user back to the Profile Page
- [x] - State
- [x] -- Static Display 
- [x] -- Default to NJ
- [x] - Zip Code (required)
- [x]  -- Validation Message:  Must be a NJ Zip Code between 07001 and 08999.

------------------

- [x] - Enter a Registered Agent Number (required)
- [x] -- Registered Agent Number must between 4-7 digits.
- [x] -User can toggle to input a Registered Agent/Office Address in substitute for Registered Agent Number
- [x] Toggle Registered Agent/Office Address
- [x] - Registered Agent Name (required)
- [x] - Registered Agent Email (required) 
- [x] -- Email Validation (correct format)
- [x] - Office Address 1 (required)
- [x] - Office Address 2
- [x] - Office City (required)
- [x] - Office State (read-only)
- [x] - Office Zip Code (required)
-- Validation Message:  Must be a NJ Zip Code between 07001 and 08999. 

------------------
Signature(s)
- [x] -- Name
- [x] --- Delete Icon (only for non-primary signer)
- [x] - Add New Signer Button
- [x] - Name (required)

------------------
Contact Information
- [x] - First Name (required - passed from Profile, edit in field)
- [x] - Last Name (required - passed from Profile, edit in field)
- [x] - Phone Number (required, edit in field)

Documents and Payment
- [x] - Individual checkboxes for documents 
- [x] - Opt-In to Annual Reports
- [x] - Opt-In to Corp Watch
- [x] - Payment Type (required)
- [x] - Disclaimer Copy ***NEEDS VALIDATION FROM THE STATE***

## Submission Process

------------------
Submission:
- Submit button

- [x] -- Validate all the page fields
- [x] -- Display page validation errors 
- [x] -- If no page validations are present, submit information via API
- [x] -- If errors are returned from the API, display error message (design to follow)
- [x] -- If API Call is successful, take the user to NIC payment page.

------------------
Payment:

 After user successfully pays:
- [ ] - Take the user back to the navigator success page with:
- [ ] -- Success Message
- [ ] -- Transaction ID
- [ ] -- Entity ID
- [ ] -- Certificate Names & IDs (Downloadable)

## Additional Acceptance Criteria
- [x] Feature Flag
- [x] Follows Design
- [x] Works in Mobile
- [ ] 508 Compliant
- [ ] Update Google Analytics

## QA Notes 12/20

- [x] Full page validation on submit
- [x] Visual Date picker bug
- [x] Submit "Authorized Representative" automatically for Title of Signer (pending Jess's approval)
- [x] Business suffix not being validated
- [x] Payment type not being validated
- [x] Form checkboxes
- [x] Submit to API
- [x] API Errors
- [x] Auto-fill fields from userData if it exists
- [x] Default contact name to split it from the name we have for the user
- [x] What to do when they have successfully submitted the form: show some text that says "You've already successfully submitted your business formation. If you haven't finished paying yet, go here: www.pay.com"
- [x] fullpage validation should confirm valid date

## Notes
- [ ] UX Review
- [ ] PO Approval

**Comment by aaronvux** [comment]
@skeeJay @Jesslax @carye3 @fiorella-io LLC Business Formation Story placeholder.

**Comment by aaronvux** [comment]
Adding API documentation below.

[BF-ExampleApiSubmit-191021-1526.pdf](https://github.com/newjersey/navigator.business.nj.gov/files/7563951/BF-ExampleApiSubmit-191021-1526.pdf)
[BF-NameAvailablecall-BusinessFormationFaxFilingAPI-191021-1527.pdf](https://github.com/newjersey/navigator.business.nj.gov/files/7563952/BF-NameAvailablecall-BusinessFormationFaxFilingAPI-191021-1527.pdf)
[BF-PrepareFilingmethod-BusinessFormationFaxFilingAPI-191021-1526.pdf](https://github.com/newjersey/navigator.business.nj.gov/files/7563953/BF-PrepareFilingmethod-BusinessFormationFaxFilingAPI-191021-1526.pdf)

**Comment by aaronvux** [comment]
@carye3 @fiorella-io removed "Steps" from the AC.  Instead, we can decide how the information is grouped and what type of design we want to move forward.  Anything marked as, "NEEDS VALIDATION FROM THE STATE" might not make the final submission to the API or we need clarification.

**Comment by aaronvux** [comment]
@kmelefsky we need to discuss this story further.  We need to communicate to the team at standup on Monday what is outstanding in the story and that In Progress and other work should take priority over this story for the first couple days of next week.

**Comment by aaronvux** [comment]
Need to find test payment URL.

**Comment by aaronvux** [comment]
Remove Members fields from this story.

- Members / Managers (optional) ***MAY BE TOTALLY UNNECESSARY FOR LLC, NEEDS VALIDATION FROM THE STATE***
- Table
-- Name
-- Address
-- Actions
--- Edit Icon
--- Delete Icon
-  Add New Member Button (limit 10 members)
-- Displays Modal
- Add button to "Use Business Address"
-- Populate fields with Business Address 
- Name (required)
- Street Address 1 (required)
- Street Address 2
- City (required)
- State
-- Dropdown with list of U.S States & District of Columbia
- Zip Code

**Comment by aaronvux** [comment]
@Jesslax outstanding fields that still need validation: Business Start Date, Main Business Address, Registered Agent Email, Signature Checkbox, Payment Disclaimer.  See the specific fields for any notes.

**Comment by aaronvux** [comment]
> @aaronvux We need these: Business Start Date, Main Business Address, Registered Agent Email Does the API require the checkbox? Otherwise, I don't think we need it. Disclaimer still waiting to hear back.

It says it is, but we could pass it if the user it not legally required to confirm their signature.
<img width="747" alt="Screen Shot 2021-12-01 at 2 32 50 PM" src="https://user-images.githubusercontent.com/36163601/144301482-82ad2980-2f49-48f9-aa1a-dbbcf2e9f8e3.png">

**Comment by aloverso** [comment]
@fiorella-io what is the strategy for showing errors when missing required fields? so far in onboarding we sometimes have a banner alert, and sometimes we have an inline message paired with a toast alert. What are we doing here?

**Comment by aloverso** [comment]
@skeeJay @aaronvux what are the specifications on the start date datepicker? It says they can only select today's date or in the future, but do we have a limit on how far into the future?

**Comment by aaronvux** [comment]
> @skeeJay @aaronvux what are the specifications on the start date datepicker? It says they can only select today's date or in the future, but do we have a limit on how far into the future?

Currently, on the existing site, there does not seem to be a limitation for the date picker.  I was able to select a date in 2060.  I have not heard that we need to restrict future dates.  Only that the date be equal to a great than today's date.

**Comment by aloverso** [comment]
we need to put *some* limit on it, from a technical perspective, how does 100 years sound?

**Comment by aaronvux** [comment]
That works.  Thank you.

**Comment by FarazA22** [comment]
@aaronvux QQ on the main business address -> city input field. The requirements mentioned this should be statically displayed with a link that routes the user back to the profile page. The designs are displaying a user editable text field. Jess may have mentioned it possibly being a dropdown. Can you provide direction on what it should be?

**Comment by aaronvux** [comment]
@FarazA22 my understanding is that the city is being pulled from the Location field in the profile which is why it is static and we are sending them back to the profile to update it.  @skeeJay please correct me if I am mistaken.

**Comment by FarazA22** [comment]
@aaronvux Within the figma design there are three check boxes under payment type that list documents. Can you confirm if the table is dynamically generated vs static? Will there be a maximum of 3 document types?

**Comment by aaronvux** [comment]
@FarazA22 for LLCs, there looks to only be 3 document types.  I don't know if there are more documents for other business structures.  Certificate of Standing and Certified Copy are optional.  Official Authenticated Formation Document is read only.  

<img width="461" alt="Screen Shot 2021-12-16 at 4 45 29 PM" src="https://user-images.githubusercontent.com/36163601/146453631-642523b6-8414-400f-9921-1f7e6d69d739.png">

**Comment by aaronvux** [comment]
@aloverso @FarazA22 did my first review.  I'll find some time for us to meet on Monday.

**Comment by aaronvux** [comment]
@Jesslax do we need the user to actually select the Title for the signature section?  There's only one option for LLC's.  So for this version, we can just pass the value automatically and update the UX for new legal structures that have more than one option.

**Comment by aaronvux** [comment]
After Review with Anne and Faraz, these items are outstanding:
- Full page validation on submit
- Visual Date picker bug
- Submit "Authorized Representative" automatically for Title of Signer (pending Jess's approval) 
- Payment type not being validated
- Form checkboxes
- Submit to API
- API Errors
- Return Successful payment & downloadable docs.

**Comment by aloverso** [comment]
@aaronvux can we update the acceptance criteria for signatures since the stuff here in the story is inaccurate, per the designs we're not doing a modal, nor checkboxes, nor the title dropdown

**Comment by FarazA22** [comment]
@aaronvux QQ, can you provide more clarity on the 'form checkboxes' outstanding item. If your referring to the documents table, it should be available in dev within the next 30 minutes.

**Comment by aaronvux** [comment]
@aloverso waiting for Jess to confirm.  I'll bring it up at grooming if she doesn't respond before then.  @FarazA22 Yup.  The documents table is what I meant.

**Comment by aloverso** [comment]
@aaronvux @Jesslax @fiorella-io it looks like the nicusa API requires contact phone number (in addition to name & email)

We already have their name & email from signin, but we don't do any checks on that. It would be a good idea for us to let the user see & verify what we'll be submitting for them for those, in case they want to change it. and also we need to ask for the phone number

**Comment by aloverso** [comment]
the ability to see & verify the name they'll be submitting is particularly important, because the API requires us to send first name & last name separately. Whereas we store the name as a single "full name" field. And so if we attempt to split that name on spaces to create first & last name, we are almost guaranteed to get it wrong in some cases, if someone has 2 first names or 2 last names. So we should definitely let them check & edit before just submitting that for them

**Comment by Jesslax** [comment]
@aaronvux what happens in the scenario where they only have to register for the Navigator after their first trial use? then they will really need the name and email screen -- when are we going to implement that?

**Comment by aloverso** [comment]
@aaronvux @Jesslax @fiorella-io another note - the API lists the EIN as a required field. We need to ask users to provide that as well, if they haven't entered it into their profile?

**Comment by aaronvux** [comment]
@let's discuss at grooming.  I thought we had the contact information fields in the original design, but could be wrong.  In the existing NJ portal EIN is optional, even though the API says it is required.

**Comment by aloverso** [comment]
Dropping some API notes here, not for this story but likely follow-up stories:
- a lot of the text fields have character maximums (ie, 50 characters for registered agent name or email, max chars for address fields, etc) so we should have frontend error message if they exceed that, I think
- same with registered agent number, we should cap it at 7 numbers the same way we do for zipcode or Entity ID or whatever

**Comment by aaronvux** [comment]
New story or add to UX story:
- a lot of the text fields have character maximums (ie, 50 characters for registered agent name or email, max chars for address fields, etc) so we should have frontend error message if they exceed that, I think
- same with registered agent number, we should cap it at 7 numbers the same way we do for zipcode or Entity ID or whatever
- Registered Agent Zip Code, must be a New Jersey zip code.

**Comment by FarazA22** [comment]
@aaronvux - We have a few more questions/comments for this ticket.

Within the business formation story there are two tasks/features we'd like to descoped from V1 ( add button to 'use business address' and select all documents checkbox ). I view both of these features as enhancements rather than something necessary to submit the formation data. 

Can you provide some clarification on where the disclaimer section should appear and point us to any designs so we can lift any draft content. @fiorella-io

Can you provide some clarity on the Payments section within the AC. Currently the success page doesn't exist. What should the experience look like when the user returns from the payment page?

**Comment by aaronvux** [comment]
I’d be good removing the select all documents checkbox, but the Use Business Address checkbox seems pretty valuable. @Jesslax thoughts?

For the success page, my understanding was a basic page was going to be built to display a success message, entity ID, transaction ID, and downloadable documents to complete the formation process.

**Comment by Jesslax** [comment]
Agree- good to remove select all boxes checkbox. Keep the use business address checkbox.

**Comment by aloverso** [comment]
@aaronvux @Jesslax we're not disagreeing that it's valuable, rather, that it's not critical for allowing a user to complete the business formation step. It can absolutely be the very next thing that we build after this story if it's high-priority, but as Faraz pointed out, it's still an enhancement to the base experience.

**Comment by aaronvux** [comment]
@aloverso @FarazA22 I hear you.  I'm going to remove it and add it to the UX Improvement story.  We can prioritize accordingly. @Jesslax

**Comment by fiorella-io** [comment]
@FarazA22 We removed the Disclaimer section and we're just adding a sentence after the Notification section. [See designs here](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6506%3A143447).

Regarding the Success page, I think for V1 it can be a simple version of the [current design](https://www.figma.com/file/408Krq8roicOzFVYrjwIdE/Navigator-Designs?node-id=6474%3A159729). As long as it lists the documents and Entity ID it should be good.

**Comment by aloverso** [comment]
@aaronvux dropping a note here to talk about when everyone's back online - the NICUSA API won't be ready for us to integrate with the final post-payment step (where we take the user back to the navigator and show their documents in our app) until early/mid-Jan so we should talk about whether we can remove that from this story and still call it done

**Comment by aaronvux** [comment]
@aloverso @FarazA22 
First Pass Review Items:
- Missing Main Business Address Section Title
- Email Address is not validating email format
- Validations still displaying on fields after they are populated and submitted
- Zip Code missing validation message when field is validated.
- On Submit with all Validations passing, not being taken to the test payment page.

**Comment by aaronvux** [comment]
@Jesslax @carye3 @fiorella-io Please review.  See my comments above for what I have already found.

**Comment by carye3** [comment]
- Any changes to the form not saved
- No location (street address or zip) validation
- No email address validation
- Contextual menus do not work (eg Annual Report reminders), instead scrolling to top of page

**Comment by fiorella-io** [comment]
- For State on both Business Location and Registered Agent, "NJ" should not use the light gray it should use color #1B1B1B
- For "Registered Agent Number" should we only allow numbers?

**Comment by FarazA22** [comment]
- [ ] add placeholder markdown files for contextual info links

**Comment by FarazA22** [comment]
@aaronvux When submitting the formation data, I'm receiving the following response. It states the minimum size for Registered Agent is 4 digits. I'll update the component so it requires a min of 4 digits.

<img width="912" alt="Screen Shot 2022-01-05 at 3 17 41 PM" src="https://user-images.githubusercontent.com/72581979/148283325-4d7f48b3-05cd-4c51-b727-6ddea2ecf66a.png">

**Comment by aaronvux** [comment]
Moving this story to done.  Google Analytics will be moved to another ticket.  Success Screen story will handle the post payment functionality.
