### ISSUE TITLE
Design QA: Biz.NJ Redesign

### ISSUE THREAD

**Issue by carye3** [newjersey/navigator.business.nj.gov#984]
QA biz.nj pages before publishing

## QA Tasks

- [X] Topic Sub-Page (Desktop)
- [ ] Topic Sub-Page (Mobile)
- [ ] Homepage (Dsk)
- [ ] Homepage (Mbl)
- [ ] Topics Landing (Dsk)
- [ ] Topics Landing (Mbl)
- [ ] Updates (Dsk)
- [ ] Updates (Mbl)
- [ ] Funding (Dsk)
- [ ] Funding (Mbl)

### Topics Page

[Figma](https://www.figma.com/file/ghMrg8szqJlL37alGeMT8j/Business.NJ.gov-Designs?node-id=6209%3A73595)

**General**
- [ ] 1.5px line weight (except sidenav) for all dividers
- [ ] Replace back to top button with thicker line weight version

**Nav Bar**
- [ ] Match padding of buttons with divider
- [ ] Replace NJ logo with png
- [ ] Change divider to grey A9AEB1
- [ ] Text weight: 500
- [ ] Dropdown menus: 24px padding on bottom and top
- [ ] Search: when typing, change text color to body text color (1B1B1B)

**Banner**
- [ ] Reduce background illustration to 15%
- [ ] Replace PNG icon with SVG 
- [ ] Description text: 20px, 350 weight
- [ ] Vertical padding 50px

**Side Nav**
- [ ] Stick to top left of screen (desktop) once you scroll beyond the fold

**Body**
- [ ] Body text weight: 300
- [ ] Header 2: remove 20px padding

## Design Tasks
- [ ] Upload hover states for all buttons
- [ ] PNG of nj logo?

**Comment by dltinnovate** [comment]
Need an updated business.nj.gov logo. Current logo has lines that run across the state outline.

**Comment by carye3** [comment]
@aaronvux updated and ready for your review
